# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Playwright E2E tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - run: npm install
    - run: npx playwright install
    - run: npm test

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      if: ${{ always() }}
      with:
        # Artifact name
        name: HTML-report
        # A file, directory or wildcard pattern that describes what to upload
        path: playwright-report
        # The desired behavior if no files are found using the provided path.
          

    
